# Generated by Django 4.1.5 on 2023-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='descricao',
            field=models.TextField(),
        ),
    ]
