# Generated by Django 4.1.5 on 2023-01-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgar', '0004_alter_pet_descricao'),
        ('adotar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoadocao',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divulgar.pet'),
        ),
        migrations.AlterField(
            model_name='pedidoadocao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
